### ISSUE TITLE
h.264 video decoder not detected

### ISSUE THREAD

**Issue by popey** [maxiberta/moonlight-snap#1] opened 2019-01-08 17:28 UTC
Thanks for making this snap!

I've been playing with it on my Ubuntu 18.04 nVidia equipped laptop. It's failing to find the h.264 decoder. I installed `vdpau-va-driver` and it's still not quite right. Here's the log of it running

```
alan@hal:~$ moonlight 
+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ glxinfo
++ grep 'OpenGL vendor'
+ VENDOR='OpenGL vendor string: NVIDIA Corporation'
+ echo VENDOR: OpenGL vendor string: NVIDIA Corporation
VENDOR: OpenGL vendor string: NVIDIA Corporation
+ [[ OpenGL vendor string: NVIDIA Corporation == *\I\n\t\e\l* ]]
+ [[ OpenGL vendor string: NVIDIA Corporation == *\N\V\I\D\I\A* ]]
+ export VDPAU_DRIVER_PATH=/var/lib/snapd/lib/gl/vdpau
+ VDPAU_DRIVER_PATH=/var/lib/snapd/lib/gl/vdpau
+ exec /snap/moonlight/12/usr/bin/moonlight
00:00:00 - Qt Warning: Qt: Session management error: None of the authentication protocols specified are supported
00:00:00 - SDL Info (0): Loading gamepad mappings from: /snap/moonlight/12/usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:00 - SDL Info (0): Loaded 131 new gamepad mappings
00:00:00 - Qt Warning: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.1149\" (uid=1000 pid=24153 comm=\"/snap/moonlight/12/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=3446 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.1149\" (uid=1000 pid=24153 comm=\"/snap/moonlight/12/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=3446 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: "Object path cannot be empty"
00:00:00 - Qt Debug: Current Moonlight version: "0.8.1"
00:00:01 - SDL Info (0): V-sync enabled
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
00:00:01 - SDL Error (0): Failed to initialize VAAPI: -1
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x55e2ec161c40] VDPAU device creation on X11 display :1 failed.
00:00:01 - SDL Error (0): Failed to create VDPAU context: -1313558101
00:00:01 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): Using SDL software renderer
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - SDL Info (0): Loading gamepad mappings from: /snap/moonlight/12/usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:01 - SDL Info (0): Loaded 0 new gamepad mappings
00:00:10 - Qt Info: "LEGION-PC" is now offline

```

**Comment by maxiberta** [comment] 2019-01-08 18:47
Hey! You've probably noticed the [video acceleration wrapper](https://github.com/maxiberta/moonlight-snap/blob/master/snap/local/va-wrapper) I copied&pasted from your contributions to the VLC snap (and this [forum topic](https://forum.snapcraft.io/t/vdpau-support-in-snaps-on-nvidia/2876/9)). Thank you!

I'm failing to reproduce on Ubuntu 16.04.5 with nvidia-410 drivers, where `libvdpau_nvidia.so` is correctly found by the snap at `VDPAU_DRIVER_PATH=/var/lib/snapd/lib/gl/vdpau`.
```
$ moonlight
+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ glxinfo
++ grep 'OpenGL vendor'
+ VENDOR='OpenGL vendor string: NVIDIA Corporation'
+ echo VENDOR: OpenGL vendor string: NVIDIA Corporation
VENDOR: OpenGL vendor string: NVIDIA Corporation
+ [[ OpenGL vendor string: NVIDIA Corporation == *\I\n\t\e\l* ]]
+ [[ OpenGL vendor string: NVIDIA Corporation == *\N\V\I\D\I\A* ]]
+ export VDPAU_DRIVER_PATH=/var/lib/snapd/lib/gl/vdpau
+ VDPAU_DRIVER_PATH=/var/lib/snapd/lib/gl/vdpau
+ exec /snap/moonlight/12/usr/bin/moonlight
00:00:00 - SDL Info (0): Loading gamepad mappings from: /snap/moonlight/12/usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:00 - SDL Info (0): Loaded 131 new gamepad mappings
00:00:00 - Qt Warning: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.63\" (uid=1000 pid=5967 comm=\"/snap/moonlight/12/usr/bin/moonlight \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1456 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
00:00:00 - Qt Warning: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.63\" (uid=1000 pid=5967 comm=\"/snap/moonlight/12/usr/bin/moonlight \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1456 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
00:00:00 - Qt Warning: "Object path cannot be empty"
00:00:00 - Qt Debug: Current Moonlight version: "0.8.1"
00:00:01 - SDL Info (0): V-sync enabled
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
00:00:01 - SDL Error (0): Failed to initialize VAAPI: -1
00:00:01 - SDL Info (0): Driver: NVIDIA VDPAU Driver Shared Library  410.78  Sat Nov 10 22:05:34 CST 2018
00:00:01 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): Using VDPAU accelerated renderer
00:00:01 - SDL Info (0): Driver: NVIDIA VDPAU Driver Shared Library  410.78  Sat Nov 10 22:05:34 CST 2018
00:00:01 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): Using VDPAU accelerated renderer
00:00:01 - SDL Info (0): Using H.264 SPS fixup
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:02 - SDL Info (0): Loading gamepad mappings from: /snap/moonlight/12/usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:02 - SDL Info (0): Loaded 0 new gamepad mappings
```

Can you please try this?

```
$ snap run --shell moonlight -c "ls -l /var/lib/snapd/lib/gl/vdpau"
total 976
lrwxrwxrwx 1 root root     20 Nov 15 18:40 libvdpau_nvidia.so -> libvdpau_nvidia.so.1
lrwxrwxrwx 1 root root     25 Nov 15 18:40 libvdpau_nvidia.so.1 -> libvdpau_nvidia.so.410.78
-rw-r--r-- 1 root root 988160 Nov 11 01:05 libvdpau_nvidia.so.410.78
```

```
$ snap version
snap    2.36.3
snapd   2.36.3
series  16
ubuntu  16.04
kernel  4.15.0-43-generic
```

**Comment by popey** [comment] 2019-01-08 22:55
```
alan@hal:~$  snap run --shell moonlight -c "ls -l /var/lib/snapd/lib/gl/vdpau"
total 0
lrwxrwxrwx 1 root alan 25 Jan  8 17:44 libvdpau_nvidia.so -> libvdpau_nvidia.so.390.77
lrwxrwxrwx 1 root alan 25 Jan  8 17:44 libvdpau_nvidia.so.1 -> libvdpau_nvidia.so.390.77
lrwxrwxrwx 1 root alan 78 Jan  8 17:44 libvdpau_nvidia.so.390.77 -> /var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77
```

```
alan@hal:~$ snap version
snap    2.36.3
snapd   2.36.3
series  16
ubuntu  18.04
kernel  4.15.0-43-generic

```

**Comment by maxiberta** [comment] 2019-01-09 05:56
What about `/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77`? Does it exist? And is it accessible by the snap, i.e. via `snap run --shell moonlight`? If not, please check kernel audit logs, I guess. Sorry, I don't have a 18.04 machine with nvidia at hand right now...

**Comment by popey** [comment] 2019-01-09 09:09
```
$ snap run --shell moonlight -c "ls -l /var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77"
-rw-r--r-- 1 root root 896160 Jul 11 06:09 /var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77

```

This feels like a snapd issue. I wonder if @zyga knows what's going on here on 18.04.

dmesg only shows these...

```
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.409:838): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input2/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.409:839): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input22/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.409:840): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input23/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.409:841): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input24/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.409:842): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input25/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.413:843): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input19/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.413:844): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input20/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.413:845): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input21/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.413:846): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/platform/i8042/serio2/input/input11/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Wed Jan  9 09:03:47 2019] audit: type=1400 audit(1547024632.413:847): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/platform/i8042/serio2/input/input11/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
Which `snappy-debug.security` interprets as:

```
alan@hal:~$ snappy-debug.security scanlog
INFO: following '/var/log/syslog'. If have dropped messages, use:
INFO: $ sudo journalctl --output=short --follow --all | sudo snappy-debug
sysctl: permission denied on key 'kernel.printk_ratelimit'
= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input2/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input2/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input2/capabilities/ev'
* adjust program to not access '/sys/devices/LNXSYSTM:[0-9]*/LNXSYBUS:[0-9]*/PNP[0-9]*C[0-9]*D:[0-9]*/input/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input22/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input22/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input22/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input23/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input23/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input23/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input24/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input24/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input24/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input25/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input25/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input25/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/[0-9]*:[0-9]*:[0-9]*.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input19/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input19/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input19/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*f.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input20/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input20/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input20/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*f.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input21/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input21/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input21/capabilities/ev'
* adjust program to not access '/sys/devices/pci[0-9]*:[0-9]*/[0-9]*:[0-9]*:[0-9]*f.[0-9]*/sound/card[0-9]*/input[0-9]*/capabilities/ev'

= AppArmor =
Time: Jan  9 09:03:52
Log: apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/sys/devices/platform/i8042/serio2/input/input11/capabilities/ev" pid=29040 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/devices/platform/i8042/serio2/input/input11/capabilities/ev (read)
Suggestions:
* adjust program to not access '/sys/devices/platform/i8042/serio2/input/input11/capabilities/ev'
* adjust program to not access '/sys/devices/platform/i[0-9]*/serio[0-9]*/input/input[0-9]*/capabilities/ev'
```

But those are likely joystick related as I haven't connected the joystick interface.

**Comment by cgutman** [comment] 2019-01-09 09:13
I reproduced this too with a similar setup to Alan.

Running strace on moonlight showed that indeed it was being denied access to the VDPAU so:
`5557  openat(AT_FDCWD, "/var/lib/snapd/lib/gl/vdpau/libvdpau_nvidia.so.1", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)`

In my system logs, I saw:
`01:06:28 moonlight: AVC apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77" pid=6448 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

**Comment by cgutman** [comment] 2019-01-09 09:28
Installing with the Snap with `--classic` fixes the issue for me, so it definitely is somehow related to the strict confinement.

**Comment by maxiberta** [comment] 2019-01-11 14:22
The `moonlight` snap in the `edge` channel now installs the `moonlight.vainfo` and `moonlight.vdpauinfo` commands to help with debugging, fwiw.

**Comment by cgutman** [comment] 2019-01-12 05:02
I see the exact same messages from running the VLC snap on this system when playing an H.264-encoded video. Playback succeeds but only because it falls back to software decoding.

`Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`

`20:53:26 vlc: AVC apparmor="DENIED" operation="open" profile="snap.vlc.vlc" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.390.77" pid=5892 comm="vlc" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

@popey This looks to me like an upstream Snappy or Ubuntu issue. Where should we report it?

**Comment by cgutman** [comment] 2019-01-18 02:07
It works out of the box now with snapd 2.37 in bionic-proposed, so the issue is technically fixed now.

However, I would like to see this roll out to all Ubuntu 18.04 users before calling this one finished.

**Comment by cgutman** [comment] 2019-01-30 02:47
It looks like snapd 2.37 is now available in the updated core snap, so this can be closed now.

I updated the [releases page](https://github.com/moonlight-stream/moonlight-qt/releases/tag/v0.8.1) and the [readme](https://github.com/moonlight-stream/moonlight-qt/blob/master/README.md) to also point to the Snap version.

**Closed as completed** 2019-01-30 03:39 UTC
